'use client';

import { Receipt, Users, AlertCircle, ChevronRight } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { formatMoney, formatDate } from '@/lib/utils';

interface LatestInvoice {
  id:            string;
  invoiceNumber: string;
  status:        string;
  total:         number;
  createdAt:     string;
}

interface BillingUser {
  id:               string;
  name:             string | null;
  email:            string;
  status:           string;
  agentCount:       number;
  invoiceCount:     number;
  latestInvoice:    LatestInvoice | null;
  totalOutstanding: number;
  monthlyTotal:     number;
}

const invoiceStatusVariant: Record<string, 'success' | 'warning' | 'danger' | 'neutral'> = {
  PAID:      'success',
  PENDING:   'warning',
  OVERDUE:   'danger',
  DRAFT:     'neutral',
  CANCELLED: 'neutral',
};

export function BillingPageClient({ users }: { users: BillingUser[] }) {
  const totalOutstanding  = users.reduce((s, u) => s + u.totalOutstanding, 0);
  const invoicedThisMonth = users.filter(u => u.latestInvoice).length;

  return (
    <div className="space-y-6">

      {/* Summary cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-white rounded-xl border border-gray-200 p-5 flex items-center gap-4">
          <div className="w-10 h-10 rounded-lg bg-[#004D3E]/10 flex items-center justify-center flex-shrink-0">
            <Users className="w-5 h-5 text-[#004D3E]" />
          </div>
          <div>
            <p className="text-xs text-gray-500 font-medium uppercase tracking-wide">Total Users</p>
            <p className="text-xl font-bold text-gray-900 mt-0.5">{users.length}</p>
          </div>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-5 flex items-center gap-4">
          <div className="w-10 h-10 rounded-lg bg-[#004D3E]/10 flex items-center justify-center flex-shrink-0">
            <Receipt className="w-5 h-5 text-[#004D3E]" />
          </div>
          <div>
            <p className="text-xs text-gray-500 font-medium uppercase tracking-wide">Invoiced This Month</p>
            <p className="text-xl font-bold text-gray-900 mt-0.5">{invoicedThisMonth}</p>
            <p className="text-xs text-gray-400">auto-generated by users</p>
          </div>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-5 flex items-center gap-4">
          <div className="w-10 h-10 rounded-lg bg-amber-50 flex items-center justify-center flex-shrink-0">
            <AlertCircle className="w-5 h-5 text-amber-500" />
          </div>
          <div>
            <p className="text-xs text-gray-500 font-medium uppercase tracking-wide">Total Outstanding</p>
            <p className="text-xl font-bold text-gray-900 mt-0.5">{formatMoney(totalOutstanding)}</p>
            <p className="text-xs text-gray-400">across all users</p>
          </div>
        </div>
      </div>

      {/* Users table */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        {users.length === 0 ? (
          <div className="p-12 text-center text-gray-400">No users found.</div>
        ) : (
          <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-100 bg-gray-50">
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">User</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Agents</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Monthly Total</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Latest Invoice</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Outstanding</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {users.map(user => (
                <tr key={user.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3">
                    <p className="font-medium text-gray-900">{user.name || '—'}</p>
                    <p className="text-xs text-gray-400">{user.email}</p>
                  </td>
                  <td className="px-4 py-3 text-gray-600">{user.agentCount}</td>
                  <td className="px-4 py-3 font-medium text-gray-900">
                    {user.monthlyTotal > 0 ? formatMoney(user.monthlyTotal) : <span className="text-gray-300">—</span>}
                  </td>
                  <td className="px-4 py-3">
                    {user.latestInvoice ? (
                      <div>
                        <p className="text-xs font-mono text-gray-700">{user.latestInvoice.invoiceNumber}</p>
                        <div className="flex items-center gap-1.5 mt-0.5">
                          <Badge variant={invoiceStatusVariant[user.latestInvoice.status] ?? 'neutral'}>
                            {user.latestInvoice.status}
                          </Badge>
                          <span className="text-xs text-gray-400">{formatDate(user.latestInvoice.createdAt)}</span>
                        </div>
                      </div>
                    ) : (
                      <span className="text-xs text-gray-300">No invoices</span>
                    )}
                  </td>
                  <td className="px-4 py-3">
                    {user.totalOutstanding > 0 ? (
                      <span className="font-medium text-amber-600">{formatMoney(user.totalOutstanding)}</span>
                    ) : (
                      <span className="text-gray-300 text-xs">—</span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <Link href={`/admin/billing/${user.id}`}>
                      <Button size="sm" variant="ghost">
                        View Invoices
                        <ChevronRight className="w-3.5 h-3.5" />
                      </Button>
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          </div>
        )}
      </div>
    </div>
  );
}
